name: SpawnX
main: xyz.derkades.spawnx.Main
version: @project.version@
authors:
  - Jim (NotKatuen)
  - Derkades
description: 'Adds /spawn and teleports players to spawn on join.'
api-version: '1.20.6'

commands:
  setspawn:
    aliases: setjoinspawn
    description: Sets the spawnpoint at the current location.
    usage: </command>
  spawn:
    description: Teleport to spawn